import type { Registry } from '..'
import {
  Acala,
  Arbitrum,
  AssetHub,
  Astar,
  Bifrost,
  Centrifuge,
  Ethereum,
  Hydration,
  Interlay,
  Kusama,
  KusamaAssetHub,
  Moonbeam,
  Mythos,
  Phala,
  Polimec,
  Polkadot,
} from './chains'
import { routes } from './routes'
import { ArbitrumTokens, EthereumTokens, PolkadotTokens } from './tokens'

/* Mainnet :: Polkadot - Ethereum */

// Assembling the Mainnet registry
export const MainnetRegistry: Registry = {
  chains: [
    Ethereum,
    Arbitrum,
    AssetHub,
    Polkadot,
    Bifrost,
    Mythos,
    Hydration,
    Acala,
    Moonbeam,
    Phala,
    Interlay,
    Polimec,
    Centrifuge,
    Astar,
    Kusama,
    KusamaAssetHub,
  ],
  tokens: [
    EthereumTokens.ETH,
    EthereumTokens.WETH,
    EthereumTokens.WBTC,
    EthereumTokens.USDC,
    EthereumTokens.USDT,
    EthereumTokens.WSTETH,
    EthereumTokens.MYTH,
    EthereumTokens.TON,
    EthereumTokens.DAI,
    EthereumTokens.LINK,
    EthereumTokens.TBTC,
    EthereumTokens.AAVE,
    EthereumTokens.LIDO,
    EthereumTokens.TRAC,
    EthereumTokens.SKY,
    EthereumTokens.SHIB,
    EthereumTokens.PEPE,

    ArbitrumTokens.ETH,
    ArbitrumTokens.USDC,

    PolkadotTokens.USDT,
    PolkadotTokens.USDC,
    PolkadotTokens.AUSDT,
    PolkadotTokens.GDOT,
    PolkadotTokens.DOT,
    PolkadotTokens.ACA,
    PolkadotTokens.CFG,
    PolkadotTokens.BNC,
    PolkadotTokens.GLMR,
    PolkadotTokens.PHA,
    PolkadotTokens.ASTR,
    PolkadotTokens.INTR,
    PolkadotTokens.PLMC,
    PolkadotTokens.VDOT,
    PolkadotTokens.IBTC,
    PolkadotTokens.MYTH,
    PolkadotTokens.HDX,
    PolkadotTokens.KILT,
    PolkadotTokens.SOL,
    PolkadotTokens.KSM,
    PolkadotTokens.KSM_BRIDGED,
  ],
  routes,
  assetUid: new Map([
    [
      AssetHub.uid,
      new Map([
        [EthereumTokens.USDC.id, { symbol: 'USDC.e' }],
        [PolkadotTokens.USDC.id, { id: '1337' }],
        [EthereumTokens.USDT.id, { symbol: 'USDT.e' }],
        [PolkadotTokens.USDT.id, { id: '1984' }],
        [EthereumTokens.WETH.id, { symbol: 'WETH.e' }],
        [EthereumTokens.WBTC.id, { symbol: 'WBTC.e' }],
      ]),
    ],
    [
      Hydration.uid,
      new Map([
        [EthereumTokens.WETH.id, { id: '1000189' }],
        [EthereumTokens.USDC.id, { id: '1000766' }],

        [PolkadotTokens.USDC.id, { id: '22' }],
        [PolkadotTokens.USDT.id, { id: '10' }],
      ]),
    ],
  ]),
}
